# core/message_types.py
"""
Defines constants for message types used in the application, primarily for
communication via queues between the CoreEngine and the GUI.

Using constants helps prevent typos and makes the codebase easier to understand
and maintain when dealing with message passing.
"""

# --- LLM Stream Related Messages ---
# These messages are typically generated by the llm_handler and processed by the GUI
# to update the display during an LLM interaction.

MSG_TYPE_LLM_CHUNK = "llm_chunk"
"""
Message type for a segment (chunk) of text streamed from the LLM.
Payload typically includes:
    - "content": (str) The text chunk.
    - "completion_tokens_live": (int) Cumulative completion tokens for the current stream.
"""

MSG_TYPE_LLM_FULL_RESPONSE = "llm_full_response"
"""
Message type indicating the complete response from the LLM has been aggregated.
While the GUI might build the display from chunks, this can be useful for other logic
or as a final confirmation.
Payload typically includes:
    - "content": (str) The full aggregated text response.
"""

MSG_TYPE_LLM_PROMPT_TOKENS_UPDATE = "llm_prompt_tokens_update"
"""
Message type to update the GUI with the calculated number of tokens for the prompt
sent to the LLM. This is usually sent before the streaming begins.
Payload typically includes:
    - "count": (int) The number of prompt tokens.
"""

MSG_TYPE_LLM_FINAL_TOKEN_COUNTS = "llm_final_token_counts"
"""
Message type for the final token counts after an LLM interaction is complete
(or has errored).
Payload typically includes:
    - "prompt_tokens": (int) Total tokens in the prompt.
    - "completion_tokens": (int) Total tokens in the completion.
    - "total_tokens": (int) Overall total tokens reported (either sum or server-reported).
"""

# --- General Status, Error, and Informational Messages ---
# These can be generated by various parts of the CoreEngine or its components.

MSG_TYPE_ERROR = "error"
"""
Message type for reporting an error to the GUI.
Payload typically includes:
    - "content": (str) A user-friendly error message.
"""

MSG_TYPE_INFO = "info"
"""
Message type for sending general informational messages to the GUI.
Payload typically includes:
    - "content": (str) The informational message.
"""

# --- OCR & Action Related Messages ---
# These messages are typically generated by the CoreEngine after OCR processing
# or when GUI actions related to OCR need to be managed.

MSG_TYPE_OCR_RESULT_FOR_ACTIONS = "ocr_result_for_actions"
"""
Message type sent when OCR processing is complete and the results (text and/or image)
are ready for the GUI to display action buttons to the user.
Payload typically includes:
    - "ocr_text": (str) The extracted OCR text.
    - "image_pil": (PIL.Image.Image) The PIL Image object that was processed.
"""

MSG_TYPE_OCR_ACTIONS_HIDE = "ocr_actions_hide"
"""
Message type to signal the GUI that any OCR-specific action buttons should be hidden,
typically reverting to the main set of buttons or an idle state.
No specific payload usually needed.
"""

# Future message types could be added here, e.g.:
# MSG_TYPE_TTS_EVENT = "tts_event" # For TTS started/finished, with sub-type in payload
# MSG_TYPE_CONFIG_UPDATED = "config_updated" # If core needs to tell GUI about a config change